# Generated by Django 6.0.8 on 2026-09-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0003_configuracoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="documento_identidade",
            field=models.FileField(
                blank=True, null=True, upload_to="clientes/documentos/"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="clientes/fotos/"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="documento_identidade",
            field=models.FileField(
                blank=True, null=True, upload_to="usuarios/documentos/"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="usuarios/fotos/"),
        ),
    ]
