# Generated by Django 6.0.8 on 2026-09-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0004_cliente_documento_identidade_cliente_foto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="estado_civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("solteiro", "Solteiro(a)"),
                    ("casado", "Casado(a)"),
                    ("divorciado", "Divorciado(a)"),
                    ("viuvo", "Viúvo(a)"),
                    ("uniao_estavel", "União estável"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="nacionalidade",
            field=models.CharField(blank=True, default="Brasileira", max_length=100),
        ),
        migrations.AddField(
            model_name="cliente",
            name="rg",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(blank=True, default="", max_length=14),
        ),
        migrations.AddField(
            model_name="usuario",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="estado_civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("solteiro", "Solteiro(a)"),
                    ("casado", "Casado(a)"),
                    ("divorciado", "Divorciado(a)"),
                    ("viuvo", "Viúvo(a)"),
                    ("uniao_estavel", "União estável"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="nacionalidade",
            field=models.CharField(blank=True, default="Brasileira", max_length=100),
        ),
        migrations.AddField(
            model_name="usuario",
            name="rg",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
