# Generated by Django 6.0.8 on 2026-09-10 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0005_cliente_estado_civil_cliente_nacionalidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="documento_identidade",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="clientes/documentos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="arquivo",
            field=models.FileField(
                upload_to="documentos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="documento_identidade",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="usuarios/documentos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    )
                ],
            ),
        ),
    ]
