# Generated by Django 5.2.17 on 2026-09-15 18:48

import advocacia.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0006_bloqueio_login_agenda_prazos_contratos_superadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacao",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentacoes_criadas",
                to="advocacia.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="documento_identidade",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="clientes/documentos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png"]
                    ),
                    advocacia.validators.validar_tamanho_documento,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clientes/fotos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    ),
                    advocacia.validators.validar_tamanho_imagem,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="numero_parcelas",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="arquivo",
            field=models.FileField(
                upload_to="documentos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    ),
                    advocacia.validators.validar_tamanho_documento,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="documento_identidade",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="usuarios/documentos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png"]
                    ),
                    advocacia.validators.validar_tamanho_documento,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="usuarios/fotos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    ),
                    advocacia.validators.validar_tamanho_imagem,
                ],
            ),
        ),
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("login_sucesso", "Login realizado"),
                            ("login_falha", "Tentativa de login falhou"),
                            (
                                "login_bloqueado",
                                "Login bloqueado por tentativas excessivas",
                            ),
                            ("criacao", "Registro criado"),
                            ("edicao", "Registro editado"),
                            ("exclusao", "Registro excluído"),
                        ],
                        max_length=20,
                    ),
                ),
                ("modelo", models.CharField(blank=True, default="", max_length=100)),
                ("objeto_id", models.PositiveIntegerField(blank=True, null=True)),
                ("descricao", models.CharField(blank=True, default="", max_length=255)),
                ("endereco_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "escritorio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_auditoria",
                        to="advocacia.escritorio",
                    ),
                ),
                (
                    "superadmin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_auditoria",
                        to="advocacia.superadmin",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_auditoria",
                        to="advocacia.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoria",
                "verbose_name_plural": "Registros de auditoria",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="TokenRedefinicaoSenha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("expira_em", models.DateTimeField()),
                ("usado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens_redefinicao_senha",
                        to="advocacia.usuario",
                    ),
                ),
            ],
        ),
    ]
