# Generated by Django 5.2.17 on 2026-09-16 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0007_movimentacao_criado_por_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="email_verificado",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="TokenVerificacaoEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("expira_em", models.DateTimeField()),
                ("usado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens_verificacao_email",
                        to="advocacia.usuario",
                    ),
                ),
            ],
        ),
    ]
