# Generated by Django 5.2.17 on 2026-09-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0008_usuario_email_verificado_tokenverificacaoemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="acao",
            field=models.CharField(
                choices=[
                    ("login_sucesso", "Login realizado"),
                    ("login_falha", "Tentativa de login falhou"),
                    ("login_bloqueado", "Login bloqueado por tentativas excessivas"),
                    ("logout", "Logout realizado"),
                    ("criacao", "Registro criado"),
                    ("edicao", "Registro editado"),
                    ("exclusao", "Registro excluído"),
                ],
                max_length=20,
            ),
        ),
    ]
