# Generated by Django 5.2.17 on 2026-09-16 01:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0009_alter_registroauditoria_acao"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="prioridade",
            field=models.CharField(
                choices=[("normal", "Normal"), ("fatal", "Prazo fatal")],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="area_direito",
            field=models.CharField(
                blank=True,
                choices=[
                    ("civel", "Cível"),
                    ("trabalhista", "Trabalhista"),
                    ("tributario", "Tributário"),
                    ("criminal", "Criminal"),
                    ("familia", "Família e Sucessões"),
                    ("previdenciario", "Previdenciário"),
                    ("empresarial", "Empresarial"),
                    ("administrativo", "Administrativo"),
                    ("consumidor", "Consumidor"),
                    ("ambiental", "Ambiental"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="comarca",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="processo",
            name="nome_advogado_adverso",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="processo",
            name="nome_parte_contraria",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="processo",
            name="oab_advogado_adverso",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="processo",
            name="percentual_honorarios_sucumbencia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="valor_causa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="vara",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
