# Generated by Django 5.2.17 on 2026-09-16 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0010_agenda_prioridade_processo_area_direito_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificacaoEnviada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("lembrete_evento", "Lembrete de compromisso ou prazo"),
                            ("resumo_semanal", "Resumo semanal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("chave", models.CharField(max_length=120)),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "agenda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificacoes_enviadas",
                        to="advocacia.agenda",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes_enviadas",
                        to="advocacia.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação enviada",
                "verbose_name_plural": "Notificações enviadas",
                "ordering": ["-enviado_em"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "chave"),
                        name="notificacao_unica_por_usuario",
                    )
                ],
            },
        ),
    ]
