# Generated by Django 5.2.17 on 2026-09-16 23:36

import advocacia.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0011_notificacaoenviada"),
    ]

    operations = [
        migrations.AddField(
            model_name="advogado",
            name="valor_hora_padrao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.CreateModel(
            name="ApontamentoHora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "minutos",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("faturavel", models.BooleanField(default=True)),
                (
                    "valor_hora",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apontamentos_hora",
                        to="advocacia.escritorio",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apontamentos_hora",
                        to="advocacia.processo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apontamentos_hora",
                        to="advocacia.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apontamento de hora",
                "verbose_name_plural": "Apontamentos de hora",
                "ordering": ["-data", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Despesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("custas", "Custas processuais"),
                            ("diligencia", "Diligência"),
                            ("copias", "Cópias e autenticações"),
                            ("viagem", "Viagem e deslocamento"),
                            ("pericia", "Honorários periciais"),
                            ("outros", "Outros"),
                        ],
                        default="custas",
                        max_length=20,
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("data", models.DateField()),
                ("reembolsavel", models.BooleanField(default=True)),
                ("reembolsada", models.BooleanField(default=False)),
                (
                    "comprovante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="despesas/comprovantes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            ),
                            advocacia.validators.validar_tamanho_documento,
                        ],
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="despesas_lancadas",
                        to="advocacia.usuario",
                    ),
                ),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesas",
                        to="advocacia.escritorio",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesas",
                        to="advocacia.processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
                "ordering": ["-data", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="SessaoUso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField()),
                ("ultima_atividade", models.DateTimeField()),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessoes_uso",
                        to="advocacia.escritorio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessoes_uso",
                        to="advocacia.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão de uso",
                "verbose_name_plural": "Sessões de uso",
                "ordering": ["-inicio"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "inicio"],
                        name="advocacia_s_usuario_cf0861_idx",
                    )
                ],
            },
        ),
    ]
