# Generated by Django 5.2.17 on 2026-09-21 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "advocacia",
            "0012_advogado_valor_hora_padrao_apontamentohora_despesa_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("procuracao", "Procuração"),
                            ("contrato", "Contrato de honorários"),
                            ("declaracao", "Declaração"),
                            ("peticao", "Petição"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        max_length=20,
                    ),
                ),
                ("conteudo", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelos_documento",
                        to="advocacia.escritorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de documento",
                "verbose_name_plural": "Modelos de documento",
                "ordering": ["nome"],
                "unique_together": {("escritorio", "nome")},
            },
        ),
    ]
