# Generated by Django 5.2.17 on 2026-09-21 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0013_modelodocumento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movimentacao",
            options={"ordering": ["-data_movimentacao"]},
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="identificador_externo",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="origem",
            field=models.CharField(
                choices=[
                    ("manual", "Lançada no sistema"),
                    ("datajud", "Importada do DataJud"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="datajud_sincronizado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="data_movimentacao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="movimentacao",
            index=models.Index(
                fields=["processo", "identificador_externo"],
                name="advocacia_m_process_2d4661_idx",
            ),
        ),
    ]
