# Generated by Django 5.2.17 on 2026-09-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0014_alter_movimentacao_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preferenciasusuario",
            name="notificacao_movimentacao",
            field=models.BooleanField(default=True),
        ),
    ]
