# Generated by Django 5.2.17 on 2026-09-22 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0016_preferenciasusuario_notificacao_tarefa_atribuida_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processo",
            name="advogado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processos",
                to="advocacia.advogado",
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processos",
                to="advocacia.cliente",
            ),
        ),
    ]
