# Generated by Django 5.2.17 on 2026-09-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0017_alter_processo_advogado_alter_processo_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="session_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
