# Generated by Django 5.2.17 on 2026-09-22 19:44

import advocacia.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0018_usuario_session_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="documento_identidade",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="clientes/documentos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png"]
                    ),
                    advocacia.validators.validar_tamanho_documento,
                    advocacia.validators.validar_assinatura_arquivo,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clientes/fotos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    ),
                    advocacia.validators.validar_tamanho_imagem,
                    advocacia.validators.validar_assinatura_arquivo,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="despesa",
            name="comprovante",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="despesas/comprovantes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png"]
                    ),
                    advocacia.validators.validar_tamanho_documento,
                    advocacia.validators.validar_assinatura_arquivo,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="arquivo",
            field=models.FileField(
                upload_to="documentos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    ),
                    advocacia.validators.validar_tamanho_documento,
                    advocacia.validators.validar_assinatura_arquivo,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="documento_identidade",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="usuarios/documentos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png"]
                    ),
                    advocacia.validators.validar_tamanho_documento,
                    advocacia.validators.validar_assinatura_arquivo,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="usuarios/fotos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    ),
                    advocacia.validators.validar_tamanho_imagem,
                    advocacia.validators.validar_assinatura_arquivo,
                ],
            ),
        ),
    ]
