# Generated by Django 5.2.17 on 2026-09-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0020_agenda_processo_opcional_e_escritorio"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cliente",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cnpj",
            field=models.CharField(blank=True, default="", max_length=18),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo_pessoa",
            field=models.CharField(
                choices=[("fisica", "Pessoa Física"), ("juridica", "Pessoa Jurídica")],
                default="fisica",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(blank=True, default="", max_length=14),
        ),
        migrations.AddConstraint(
            model_name="cliente",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cpf", ""), _negated=True),
                fields=("escritorio", "cpf"),
                name="cliente_escritorio_cpf_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="cliente",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cnpj", ""), _negated=True),
                fields=("escritorio", "cnpj"),
                name="cliente_escritorio_cnpj_unico",
            ),
        ),
    ]
