# Generated by Django 5.2.17 on 2026-10-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0021_cliente_pessoa_fisica_juridica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("advogado", "Advogado"),
                    ("estagiario", "Estagiário"),
                    ("financeiro", "Financeiro"),
                    ("secretaria", "Secretária"),
                ],
                max_length=20,
            ),
        ),
    ]
