# Generated by Django 5.2.17 on 2026-10-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0022_perfis_de_acesso"),
    ]

    operations = [
        migrations.AddField(
            model_name="processo",
            name="sigiloso",
            field=models.BooleanField(default=False),
        ),
    ]
