# Generated by Django 5.2.17 on 2026-10-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0023_processo_sigiloso"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="totp_ativo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="totp_segredo",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="usuario",
            name="totp_ultimo_passo",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
