# Generated by Django 5.2.17 on 2026-10-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0024_verificacao_duas_etapas"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="anonimizado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="consentimento_lgpd",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="consentimento_lgpd_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registroauditoria",
            name="acao",
            field=models.CharField(
                choices=[
                    ("login_sucesso", "Login realizado"),
                    ("login_falha", "Tentativa de login falhou"),
                    ("login_bloqueado", "Login bloqueado por tentativas excessivas"),
                    ("logout", "Logout realizado"),
                    ("criacao", "Registro criado"),
                    ("edicao", "Registro editado"),
                    ("exclusao", "Registro excluído"),
                    ("exportacao", "Dados exportados"),
                ],
                max_length=20,
            ),
        ),
    ]
