# Generated by Django 5.2.17 on 2026-10-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0025_lgpd_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="agenda_feed_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
