# Generated by Django 5.2.17 on 2026-10-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0026_agenda_ics"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoescritorio",
            name="chave_pix",
            field=models.CharField(blank=True, default="", max_length=77),
        ),
        migrations.AddField(
            model_name="configuracaoescritorio",
            name="cidade_pix",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AddField(
            model_name="configuracaoescritorio",
            name="nome_recebedor_pix",
            field=models.CharField(blank=True, default="", max_length=25),
        ),
        migrations.AddField(
            model_name="configuracaoescritorio",
            name="tipo_chave_pix",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cpf_cnpj", "CPF ou CNPJ"),
                    ("email", "E-mail"),
                    ("telefone", "Celular"),
                    ("aleatoria", "Chave aleatória"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
