# Generated by Django 5.2.17 on 2026-10-07 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0027_pix_escritorio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intimacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificador_externo", models.CharField(max_length=120)),
                (
                    "numero_processo",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("tribunal", models.CharField(blank=True, default="", max_length=20)),
                ("orgao", models.CharField(blank=True, default="", max_length=255)),
                (
                    "tipo_comunicacao",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("texto", models.TextField(blank=True, default="")),
                ("link", models.URLField(blank=True, default="", max_length=500)),
                ("data_disponibilizacao", models.DateField()),
                ("data_publicacao", models.DateField()),
                ("prazo_dias", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("prazo_dias_uteis", models.BooleanField(default=True)),
                ("prazo_estimado", models.BooleanField(default=False)),
                ("prazo_final", models.DateField(blank=True, null=True)),
                ("lida", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "advogado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intimacoes",
                        to="advocacia.advogado",
                    ),
                ),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intimacoes",
                        to="advocacia.escritorio",
                    ),
                ),
                (
                    "evento_agenda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intimacoes",
                        to="advocacia.agenda",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intimacoes",
                        to="advocacia.processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intimação",
                "verbose_name_plural": "Intimações",
                "ordering": ["-data_disponibilizacao", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("escritorio", "identificador_externo"),
                        name="intimacao_unica_por_escritorio",
                    )
                ],
            },
        ),
    ]
