# Generated by Django 5.2.17 on 2026-10-07 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advocacia", "0029_inscricao_push"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeriadoLocal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("descricao", models.CharField(max_length=120)),
                (
                    "abrangencia",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("anual", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feriados_locais",
                        to="advocacia.escritorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feriado local",
                "verbose_name_plural": "Feriados locais",
                "ordering": ["data"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("escritorio", "data"),
                        name="feriado_local_unico_por_data",
                    )
                ],
            },
        ),
    ]
