# Generated by Django 6.0.8 on 2026-10-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocacia', '0031_remove_app_api'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feriadolocal',
            name='feriado_local_unico_por_data',
        ),
        migrations.AddConstraint(
            model_name='feriadolocal',
            constraint=models.UniqueConstraint(fields=('escritorio', 'data', 'abrangencia'), name='feriado_local_unico_por_local'),
        ),
    ]
